version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./template.png:/app/template.png
      - ./font.ttf:/app/font.ttf
    environment:
      - PORT=8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
